from typing import Final

BLACK: Final[int]
WHITE: Final[int]
TOTAL_INPUT_PLANES: Final[int]

class Board:
    def __init__(self, width: int, height: int) -> None: ...
    @staticmethod
    def standard() -> Board: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def get_piece(self, col: int, row: int) -> int | None: ...
    def set_piece(self, col: int, row: int, piece: int | None) -> None: ...
    def clear(self) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Game:
    def __init__(self, width: int, height: int) -> None: ...
    @staticmethod
    def with_komi(width: int, height: int, komi: float) -> Game: ...
    @staticmethod
    def standard() -> Game: ...
    def komi(self) -> float: ...
    def score(self) -> tuple[float, float]: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def get_piece(self, col: int, row: int) -> int | None: ...
    def set_piece(self, col: int, row: int, piece: int | None) -> None: ...
    def turn(self) -> int: ...
    def is_over(self) -> bool: ...
    def legal_action_indices(self) -> list[int]: ...
    def apply_action(self, action: int) -> bool: ...
    def action_size(self) -> int: ...
    def board_shape(self) -> tuple[int, int]: ...
    def input_plane_count(self) -> int: ...
    def reward_absolute(self) -> float: ...
    def reward_from_perspective(self, perspective: int) -> float: ...
    def name(self) -> str: ...
    def outcome(self) -> GameOutcome | None: ...
    def legal_moves(self) -> list[Move]: ...
    def is_legal_move(self, move_: Move) -> bool: ...
    def make_move(self, move_: Move) -> bool: ...
    def unmake_move(self) -> bool: ...
    def board(self) -> Board: ...
    def ko_point(self) -> tuple[int, int] | None: ...
    def clone(self) -> Game: ...
    def __hash__(self) -> int: ...
    def encode_game_planes(self) -> list[list[list[float]]]: ...
    def encode_board_planes(self) -> list[list[list[float]]]: ...
    def decode_action(self, action: int) -> Move | None: ...
    def total_actions(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Move:
    @staticmethod
    def place(col: int, row: int) -> Move: ...
    @staticmethod
    def pass_move() -> Move: ...
    def is_pass(self) -> bool: ...
    def col(self) -> int | None: ...
    def row(self) -> int | None: ...
    def encode(self, board_width: int, board_height: int) -> int: ...
    @staticmethod
    def decode(action: int, board_width: int, board_height: int) -> Move: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: Move) -> bool: ...
    def __hash__(self) -> int: ...

class GameOutcome:
    def winner(self) -> int | None: ...
    def encode_winner_absolute(self) -> float: ...
    def encode_winner_from_perspective(self, perspective: int) -> float: ...
    def is_draw(self) -> bool: ...
    def name(self) -> str: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: GameOutcome) -> bool: ...
